visdesignlab/Sanguine

backend/api/api/tests.py
backend/api/api/views.py

Remove the check for patient ids allowing the request to return all the patients at once.
Related to #13

Allow all pats from risk_score and from patient_outcomes

---

frontend/src/Components/Charts/ChartAccessories/AnnotationForm.tsx
frontend/src/Components/Modals/ManageStateDialog.tsx
frontend/src/Components/Modals/SaveStateModal.tsx
frontend/src/Components/Modals/StateAccessControl.tsx
frontend/src/Components/Modals/UIDInputModal.tsx
frontend/src/Components/Utilities/LeftToolBox/LeftToolBox.tsx
frontend/src/Components/Utilities/TopMenu/RegularModeMenu.tsx
frontend/src/Components/Utilities/TopMenu/StateManagementSuite.tsx
frontend/src/Dashboard.tsx
frontend/src/Interfaces/ProjectConfigStore.ts

resolves #158

---

backend/api/api/views.py
frontend/src/Components/Utilities/DetailView/CaseInfo.tsx

Closes #188
Adds the logic to return all cleaned cpt code names from a surgery query. For example:
```
{
"result": [
{
...
"cpt": [
"Thoracic Aorta Aneurysm Procedure",
"CABG",
"ECMO"
]
}
]
}
```
A current by-product of this fix is that the visit number is now also returned as "hospital visit number" in the JSON. I guess that's not a huge issue, but we should probably not display that in the UI.

Add cpt codes to surgery query

---

README.md
backend/api/api/views.py

These response types fix the response codes for the returns. This will be useful for debugging and for catching errors on the fronend
I also reorderd the README for easier copy and paste on the server

Fix http response types from API and reorder the README

---

backend/README.md
backend/api/api/urls.py
backend/api/api/utils.py
backend/api/api/views.py
frontend/src/App.tsx
frontend/src/Components/Charts/CostBarChart/StackedBarChart.tsx
frontend/src/Components/Charts/CostBarChart/WrapperCostBar.tsx
frontend/src/Components/Charts/DumbbellChart/WrapperDumbbell.tsx
frontend/src/Components/Charts/HeatMap/WrapperHeatMap.tsx
frontend/src/Components/Charts/ScatterPlot/WrapperScatter.tsx
frontend/src/Components/Utilities/LeftToolBox/CurrentView.tsx
frontend/src/Components/Utilities/LeftToolBox/LeftToolBox.tsx
frontend/src/Components/Utilities/LeftToolBox/SurgeryListViewer.tsx
frontend/src/Components/Utilities/TopMenu/AddModeTopMenu.tsx
frontend/src/Components/Utilities/TopMenu/RegularModeMenu.tsx
frontend/src/HelperFunctions/Clipboard.ts
frontend/src/HelperFunctions/ProcedureStringGenerator.tsx
frontend/src/Interfaces/Actions/SelectionActions.ts
frontend/src/Interfaces/ProjectConfigStore.ts
frontend/src/Interfaces/SelectionStore.ts
frontend/src/Interfaces/Types/DataTypes.ts
frontend/src/Interfaces/Types/StateTypes.ts

Goal: Show the overlapping procedure with a list expansion on selection
@JackWilb I got most of the front end stuff finished. We will need to have the backend to provide the lists and work with new filters.

Procedure Expansion Patch

---

backend/api/api/utils.py
backend/api/api/views.py
frontend/src/App.tsx
frontend/src/Components/Utilities/LeftToolBox/SurgeryListViewer.tsx
frontend/src/Interfaces/Actions/SelectionActions.ts
frontend/src/Interfaces/ProjectConfigStore.ts

For example, this shows how many CABGs happened without co-occurring with another surgery type.
You can also request the `Only CABG` from `request_transfused_units` and it will return the cases that match. This should work with the AND/OR logic of the query

Add a count for procedures that happened without an overlap and add ability to query for those types of surgery in request transfused units

---

frontend/src/Components/Charts/ChartAccessories/CustomizedAxisBand.tsx

Closes #307 
**_Bug_**: Issue #307 Scatter plot x-axis bin labels did not contain text.
**_Fix_**: Scatter plot x-axis bin labels _now contain text._
**_Changes_**: 
- CustomizedAxisBand.tsx: Added a 'y' property to <AxisText> to vertically center text in bins.
- StyledSVGComponents.ts: Changed AxisText to 'styled.text'.
After:
TODOs:

Fix: Scatter Plot X-Axis Bin Labels (#307)

---

frontend/src/Components/Charts/CostBarChart.tsx

Closes #321 
Cost / Savings chart toggle defaults 'on'.
Default before:
Default after:
TODOs:

Toggle defaults to 'on'

---

frontend/src/Components/Charts/ChartAccessories/ExtraPairPlots/ExtraPairViolin.tsx
frontend/src/Components/Charts/ChartAccessories/ExtraPairPlots/GeneratorExtraPair.tsx
frontend/src/HelperFunctions/ExtraPairDataGenerator.ts
frontend/src/Presets/DataDict.ts

Closes #312 
Issue #312: Datapoints were scattered out-of-bounds in 'additional attribute' columns which contain violin plots
This PR:
- Changes the datapoint scaling from static domains to dynamic data-based domains.
- Ensures that all violin plots and datapoints (within each additional attribute) internally have the same horizontal scaling. 
Before:
After:
TODOs:

Fix: Heatmap Attribute Data Scaling (#312)

---

frontend/src/Components/Charts/DumbbellChart/DumbbellChart.tsx
frontend/src/Components/Charts/DumbbellChart/WrapperDumbbell.tsx

Closes #329 
Issue 329 - There are now only two 'Show' options for dumbbell chart buttons. 'Sort By' buttons only appear when 'shown'.
Here are two different states of button clicks from this PR, demonstrating these changes: 
TODOs:

Reduce Dumbbell Chart Buttons (#329)

---

frontend/src/Components/Charts/ChartAccessories/CustomizedAxisOrdinal.tsx
frontend/src/Components/Charts/DumbbellChart/DumbbellChart.tsx
frontend/src/Presets/StyledSVGComponents.ts

Closes #328 
Before:
- Difficult to visually separate columns
After: 
- Columns are visually separated by light shade of grey, alternating.
Before:
After:
TODOs:

Dumbbell Chart Column Shading (#328)

---

frontend/src/Components/Charts/ChartAccessories/CustomizedAxisBand.tsx
frontend/src/Components/Charts/ScatterPlot/ScatterPlot.tsx

Closes #337 
Same as #334 but for scatterplots. Slight alternating column shading is better for visual separation.
TODOs:

Column Shading on Scatterplots (#337)

---

frontend/src/Components/Charts/ChartAccessories/CustomizedAxisBand.tsx
frontend/src/Components/Charts/ChartAccessories/CustomizedAxisOrdinal.tsx
frontend/src/Components/Charts/DumbbellChart/DumbbellChart.tsx
frontend/src/Components/Charts/DumbbellChart/SingleDumbbell.tsx
frontend/src/Components/Charts/ScatterPlot/ScatterPlot.tsx
frontend/src/Components/Utilities/LeftToolBox/SurgeryListViewer.tsx
frontend/src/Components/Utilities/LeftToolBox/SurgeryRow.tsx
frontend/src/Interfaces/HoverStore.ts
frontend/src/Interfaces/Store.ts
frontend/src/Presets/StyledComponents.ts
frontend/src/Presets/StyledSVGComponents.ts

Does not end #327 quite yet, because we want to apply highlighting to _all charts._
This PR just for dumbbell charts + scatter plots.
On hover, dumbbell charts and scatter plots have cross-highlighting between them.
- Highlighting (hovering) a _column_ or _individual datapoint (case)_ in either the dumbbell chart or the scatter plot, highlights all corresponding points (_cases_) in the other chart.
**Caveat:** To highlight a column in a scatterplot, hover over its column label.
https://github.com/user-attachments/assets/4c5e05e5-19e2-48ea-bc63-53ba9c6a23ae
TODOs:

Hover Highlight - Dumbbell and Heatmap (#327)

---

frontend/src/Components/Charts/HeatMap/HeatMap.tsx
frontend/src/Interfaces/HoverStore.ts

This PR is another short step _towards_ #327 .
1. _Before_ finishing #327,  I want to finish #348 
2. _Then_ I will complete the hovering for Cost Savings Chart.
Hovering on rows works for heatmap - updates store and subsequently other charts.
TODOs:

Heatmap Hovering

---

frontend/src/Components/Charts/DumbbellChart/DumbbellChart.tsx

Closes #365 
As described in #365 , dumbbell charts were not fully clearing when multiple procedure selections resulted in no cases (no data).
**Before** (Multiple selections which result in zero cases, crashes the chart):
**After:** (Multiple selections which result in zero cases, results in a clear chart like it should):
None

Fix: Dumbbell Charts Clear If Without Data (#365)

---

frontend/src/Components/Utilities/LeftToolBox/SurgeryListViewer.tsx
frontend/src/Components/Utilities/LeftToolBox/SurgeryRow.tsx

Closes #311 #336 
The procedure selection previously was
- Duplicating Selections
- Duplicating expanded procedure lists
- Expanded lists would not collapse again on toggle
- Icons were triangles not arrows
This PR fixes those issues, and changes the styles of expand/collapse toggle icons. 
**Before** (For example: Clicking on procedures wasn't working, toggle collapse wasn't working)
https://github.com/user-attachments/assets/2890583d-bbf0-4ec1-9ca7-1a623056cc54
**After**
https://github.com/user-attachments/assets/1137e7b8-3218-44d9-bba2-784487e4dffa
None

 Fix: Procedure Button Errors & Styles (#311, #336)

---

backend/api/views/sql_queries/mariadb.py

No
Raised by Jing Zhang - University of Washington
'VENT' was returning all one value. 
Switched the SQL for 
`VST.TOTAL_VENT_MINS > 1440, 1, 0 AS VENT,`  
into  
`VST.total_vent_mins > 1440 AS VENT,` to return the proper boolean.
Before & After
None

Fix: Missing Vent Data

---

frontend/src/Components/Charts/HeatMap/WrapperHeatMap.tsx

Closes #364 
The 'Outcome Comparison' true / false count totals were flipped.
Before: If an attribute (ECMO, TXA etc) had an SQL-returned value of 0, it was marked as true, all else false.
After: If an attribute (ECMO, TXA etc) had an SQL-returned value of 0, it is marked as false, all else true.

Fix: True False Counts (#364)

---

frontend/src/Components/Charts/ChartAccessories/CustomizedAxisOrdinal.tsx
frontend/src/Components/Charts/ChartAccessories/HeatMapAxisY.tsx
frontend/src/Components/Charts/CostBarChart.tsx
frontend/src/Components/Charts/HeatMap/WrapperHeatMap.tsx
frontend/src/Components/Hooks/PrivateModeLabeling.tsx

Closes #371 
Some charts were not showing provider names instead of codes when private mode is off.
Before:
After:
None

Fix: Provider Names Now Appear (#371)

---

frontend/src/Presets/Constants.ts

More default room for y-axis labels to avoid truncation
None

Labels Have More Room

---

frontend/src/Components/Charts/ChartAccessories/ExtraPairButtons.tsx
frontend/src/Components/Charts/CostBarChart.tsx
frontend/src/Components/Charts/HeatMap/WrapperHeatMap.tsx
frontend/src/HelperFunctions/ExtraPairDataGenerator.ts
frontend/src/Presets/DataDict.ts

Closes #325  
**Re-do of #331**
**_Before:_** #325 - Some 'additional attributes' data in the cost / savings chart were all the same value: `Total Transfused`, `Zero Transfused`, and `Per Case`.
**_Changes:_** 
- Re-used the (correct) additional-attribute data generation from `WrapperHeatMap.tsx`, into `CostBarChart.tsx`.
- `WrapperHeatMap.tsx` now generates and uses data _separately_ for the cost / savings chart vs. the additional attribute charts.
**_After:_**  The cost savings chart's 'additional attributes' have correct data (like the Heat Map does)
**_Caveats:_** 
- Cost / Savings chart's additional attributes are only in terms of `PRBC_UNITS` right now (because this chart has no x-axis options other than `Cost`). 
- `WrapperHeatMap` and `CostBarChart` should be refactored. For …

Fix: Cost/Savings Extra Plot Data Missing

---

frontend/src/Interfaces/Store.ts

Closes #391
When selecting multiple procedures and sub-procedures, it was using AND logic instead of OR logic.
Ex: (CABG OR ECMO) was actually filtering with CABG _AND_ ECMO. This has been fixed for procedures and sub-procedures.
Before:
After:

Fix: Multiple Procedure Selection Logic (#391)

---

frontend/src/Components/Utilities/TopMenu/RegularModeMenu.tsx

Requested by Nik Krumm, U.W.
Makes private mode more clear via a toggle.
https://github.com/user-attachments/assets/78cd1b02-ab0b-4b33-8319-885bea9f2d8b

Private toggle switch

---

frontend/package.json
frontend/src/Components/Charts/ChartAccessories/HeatMapAxisY.css
frontend/src/Components/Charts/ChartAccessories/HeatMapAxisY.tsx
frontend/src/Components/Charts/HeatMap/HeatMap.tsx
frontend/src/Components/Hooks/PrivateModeLabeling.tsx
frontend/yarn.lock

1. Truncates Provider Names which were overlapping on UW's implementation
2. Tooltip hover functionality to see provider name
3. Provider display name (as opposed to tooltip) is _normalized_ in the format: [title, last, first] and catches many exceptions.
**Normalizing Names:**
Here is a test dataset of randomly generated names in all sorts of formats and casings
- Some include titles like 'Doctor' 'Dr.' or no title at all. 
- Some are first, last others are last, first.
The names are normalized on display, but made fully available by tooltip hover.
https://github.com/user-attachments/assets/37887db8-11f5-4ba1-aaa8-fc6a9088e9bf

Fix: Normalize & Truncate Provider Names

---

frontend/src/Components/Charts/ChartAccessories/HeatMapAxisX.tsx
frontend/src/Presets/Constants.ts

Closes #425 
Read #425 raised by Jing Zhang, U.W.
Labels for cell salvage heatmap are now 1,2,3..N+ in units of 100mL
Before:
After:

Fix: Cell Salvage Heatmap Labels (#425)
